### ISSUE TITLE
 Conducting sanity checks on Testground by performing similar tests on Knuu and comparing the results

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-core#1262] opened 2024-03-11 16:48 UTC
All big-block-workstream experiments were carried out on the testground platform, and results were generated using that backend. Some concerns have arisen regarding aspects of the gathered data, such as the occurrence of duplicate gossiped block parts between peers, which appears inconsistent with the expected behavior of the consensus reactor. Therefore, it would be beneficial to perform sanity checks using an alternative backend, specifically [Knuu](https://github.com/celestiaorg/knuu), to compare the results, including network throughput, and verify that there are no significant discrepancies.

**Comment by evan-forbes** [comment] 2024-06-10 14:19
I'm closing this in favor of the issue is app https://github.com/celestiaorg/celestia-app/issues/3147

**Closed by evan-forbes** 2024-06-10 14:19 UTC
Labels: WS: Big Blonks 🔭

**Comment by staheri14** [comment] 2024-06-10 23:29
This one had already been added in the other issue https://github.com/celestiaorg/celestia-app/issues/3147 as a bonus 
> We can additionally or as the next step address https://github.com/celestiaorg/celestia-core/issues/1262. 

Now that it is closed, would be good to move its content to that issue.
